blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogs, name='blogs'),
    path('<int:blog_id>/', views.blog_info, name='blog_info')
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blogs/', include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateField()
    content = models.TextField(blank=True)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def blogs(request):
    db_blogs = Blog.objects.order_by('-date')

    return render(request, 'blog/blogs.html', {'blogs': db_blogs})


def blog_info(request, blog_id: int):
    blog = get_object_or_404(Blog, pk=blog_id)

    return render(request, 'blog/blog_info.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project


def index(request):
    projects = Project.objects.all()

    return render(request, 'portfolio/index.html', {'projects': projects})

blog/templates/blog/blog_info.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Blogs {% endblock title %}

{% block content %}
    {% include 'includes/navbar.html' %}
    <h1>{{ blog.title }}</h1>
    <h2>{{ blog.date }}</h2>
    <p>{{ blog.content }}</p>
{% endblock content %}

blog/templates/blog/blogs.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Blogs {% endblock title %}

{% block content %}
    {% include 'includes/navbar.html' %}
    <h1>Ivan has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h1>
    {% for blog in blogs %}
        <h2><a href="{% url 'blog:blog_info' blog.id %}">{{ blog.title }}</a></h2>
        <h4>{{ blog.date }}</h4>
        <p>{{ blog.content|truncatechars:100 }}</p>
    {% endfor %}
{% endblock content %}

portfolio/templates/portfolio/index.html
{% extends 'base.html' %}

{% load static %}

{% block css_additional %} <link rel="stylesheet" href="{% static 'portfolio/css/index.css' %}"> {% endblock css_additional %}

{% block title %} My Fucking Portfolio {% endblock title %}

{% block content %}
    {% include 'includes/navbar.html' %}
    <img id="main-photo" src="{% static 'portfolio/img/IMG-178.jpg' %}" alt="">
    <h1 id="IvanMinyaev">Ivan<br>Minyaev</h1>

    <h3><a href="{% url 'blog:blogs' %}">Blogs</a></h3>
    
    {% for project in projects %}
        <p>{{ project.title }}</p>
        <p>{{ project.description }}</p>
        <img src="{{ project.image.url }}" alt="sfd" width="200px">
        {% if project.url %}
            <br> <a href="{{ project.url }}">Link</a>
        {% endif %}
    {% endfor %}
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block css_additional %}{% endblock css_additional %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">   
        <title>{% block title %}{% endblock title %}</title>
    </head>
    <body>
        {% block content %}{% endblock content %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    </body>
</html>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
        </li>
        </ul>
        <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
    </div>
</nav>